### ISSUE TITLE
Rust module doesn't contain MR#13

### ISSUE THREAD

**Issue by dmulder** [kanidm/compact-jwt#14]
The compact-jwt module still doesn't have [MR#13](https://github.com/kanidm/compact-jwt/pull/13), so I'm having to build Himmelblau against compact-jwt main branch. Is there some process that needs to be triggered to submit the changes to the module?

**Comment by Firstyear** [comment]
The process is "whenever william does cargo publish". At the moment I want to get the JWE stuff a bit more polished then we can do an update :)
